apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-vpc-demo
  labels:
    app: crossplane-vpc-demo
spec:
 project: dan-a-eks
 source:
   repoURL: https://github.com/danamzulescu-codefresh/argocd-demo-repo
   path: K8s-Resources/Dev-Dan/Applications/crossplane-demo
 destination:
   namespace: crossplane-vpc-demo
   name: in-cluster
 syncPolicy:
   automated: {}
   syncOptions:
     - CreateNamespace=true
