apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: dan-a-eks
  source:
    path: K8s-Resources/Dev-Dan/Applications/helm-nginx
    repoURL: https://github.com/danamzulescu-codefresh/argocd-demo-repo
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service.type
          value: ClusterIP
  destination:
    name: in-cluster
    namespace: nginx-app
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
