apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: official-canary-rollout
spec:
  project: dan-a-eks
  source:
    path: K8s-Resources/Dev-Dan/Applications/official-rollouts-demo/canary
    repoURL: https://github.com/danamzulescu-codefresh/argocd-demo-repo
    targetRevision: HEAD
  destination:
    namespace: dan-a-eks
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
